### ISSUE TITLE
Icons 9.10, 10.42, 10.45 is empty

### ISSUE THREAD

**Issue by slavakrampetz** [NarekChang/NeededIcons#1]
These icons present on PNG, but not in fonts / JS.

**Comment by NarekChang** [comment]
@slavakrampetz Are you sure that you understand it? Please, check everything again.

**Comment by slavakrampetz** [comment]
May be I've got something wrong, but when I look into file `config.json`, https://github.com/NarekChang/NeededIcons/blob/master/config.json for icon 9.10, `svg.path` is empty:
```json
{
  "uid": "c4b1624fc1f992350d2cc4f06bab17c1",
  "css": "9.10",
  "code": 59515,
  "src": "custom_icons",
  "selected": true,
  "svg": {
    "path": "",
    "width": 1000
  },
  "search": [
    "9.10"
 ]
}
```
Same for icons 10.42, 10.45.

All other icons have `path` filled, e.g.
```json
{
  "uid": "b980058f036c571dfc06484bffe606ba",
  "css": "9.11",
  "code": 59516,
  "src": "custom_icons",
  "selected": true,
  "svg": {
    "path": "M352.1 692L823.5 220.6C839.8 204.3 866.1 204.2 882.5 220.6 898.7 236.8 898.6 263.3 882.4 279.5L381.6 780.3 381.6 780.3 381.6 780.4C365.3 796.6 339 796.7 322.7 780.4L116.4 574C100.1 557.8 100 531.6 116.4 515.2 132.7 498.9 159 498.9 175.3 515.1L352.1 692Z",
    "width": 1000
  },
...
```
As result, in file `font/neededicons.svg` `d` attribute is empty for SVG font glyph
```svg
<glyph glyph-name="9.10" unicode="&#xe87b;" d="" horiz-adv-x="1000" />
```

And, finally, at `demo.html` from these icons is empty too, see screenshot:
![image](https://user-images.githubusercontent.com/25292491/33536641-dab1e70e-d8e8-11e7-9520-b8a7850b687a.png)

**Comment by NarekChang** [comment]
@slavakrampetz I understood you. I will fixed it today. Thanks you!
